# Generated by Django 4.1.7 on 2023-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostermanager', '0004_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(default='2023-06-30'),
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(default='2022-23 Season', max_length=255),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(default='2022-07-01'),
        ),
    ]
