# Generated by Django 4.1.7 on 2023-03-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField()),
                ('forward1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Forward 1:')),
                ('forward2', models.CharField(blank=True, max_length=2, null=True, verbose_name='Forward 2:')),
                ('forward3', models.CharField(blank=True, max_length=2, null=True, verbose_name='Forward 3:')),
                ('defense1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Defense 1:')),
                ('defense2', models.CharField(blank=True, max_length=2, null=True, verbose_name='Defense 2:')),
                ('goalie', models.CharField(blank=True, max_length=2, null=True, verbose_name='Goalie:')),
                ('ext_attacker', models.CharField(blank=True, max_length=2, null=True, verbose_name='Ext:')),
                ('special_teams', models.CharField(max_length=20)),
                ('extra_attacker', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=5)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
